version: 0.1.0.{build}

image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 1

branches:
  only:
  - master

cache:
- packages -> **\packages.config

test: off

assembly_info:
  patch: true
  file: Properties\AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
- cmd: nuget restore

build:
  project: NFive.sln
  verbosity: minimal

after_build:
- cmd: 7z a nfive.zip *.dll nfive.yml nfive.lock __resource.lua index.html config\

artifacts:
- path: nfive.zip
  name: NFive

for:
-
  branches:
    only:
      - master

  environment:
    BT_USER:
      secure: WeKwDVyYUZltHMzCsNlq5w==
    BT_KEY:
      secure: piTpGhOfvdvWqMnPTWkLyuX/b1lHDazzSWt37UbgqUHCAdfsEb+0exY7AUnYzT7Z

  deploy_script:
  - curl -s -w "\n" -T "nfive.zip" -u"%BT_USER%:%BT_KEY%" "https://api.bintray.com/content/nfive/NFive/NFive/%BUILD_VERSION_FILE%/%BUILD_VERSION_FILE%/nfive.zip?publish=1"
