name: Continuous Integration

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "**"

jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      assemblySemVer: ${{ steps.gitversion.outputs.assemblySemVer }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true
          configFilePath: ./.github/version.yml

  build:
    runs-on: windows-latest
    needs: calculate-version
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}
      ASSEMBLYSEMVER: ${{ needs.calculate-version.outputs.assemblySemVer }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore dependencies
        run: nuget restore NFive.sln

      - name: Build the solution
        run: dotnet build -c Release -o Build /p:Version=${{env.ASSEMBLYSEMVER}} NFive.sln

      - name: Prepare build artifact
        shell: pwsh
        run: |
          New-Item "Build" -itemType Directory
          Copy-Item -Path ".\Server\Build\*.dll" -Destination ".\Build" -PassThru -Force -Exclude CitizenFX.Core.Server.dll 
          Copy-Item -Path ".\Client\Build\*.dll" -Destination ".\Build" -PassThru -Force -Exclude CitizenFX.Core.Client.dll
          Copy-Item -Path ".\lib\*.dll" -Destination ".\Build" -PassThru -Force
          Copy-Item .\README.md,.\LICENSE,.\nfive.yml,.\nfive.lock,.\fxmanifest.lua,.\index.html -PassThru -Destination ".\Build"
          New-Item ".\Build\config" -itemType Directory
          Copy-Item .\config\* -Destination ".\Build\config" -PassThru -Recurse

      - name: Attach Zip as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: NFive-${{ env.SEMVER }}
          path: Build